### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 128-132: ordinal not in range(128)

### ISSUE THREAD

**Issue by markeyev** [trac-hacks/ticket2rtm#1]
==== How to Reproduce ====

While doing a POST operation on `/newticket`, Trac issued an internal error.

''(please provide additional details here)''

Request parameters:
{{{
{'__FORM_TOKEN': u'211b253da3ba1dfe43f57944',
 'field_cc': u'',
 'field_component': u'System',
 'field_description': u'\u3069\u3046\u3057\u3066\u767b\u9332\u3057\u3066\u304f\u308c\u306a\u3044\u306e\uff01',
 'field_keywords': u'',
 'field_milestone': u'',
 'field_owner': u'',
 'field_priority': u'major',
 'field_reporter': u'bindi',
 'field_summary': u'Remember The Milk \u3068\u306e\u9023\u643a',
 'field_type': u'defect',
 'field_version': u'',
 'submit': u'\u30c1\u30b1\u30c3\u30c8\u3092\u767b\u9332\u3059\u308b'}
}}}

User Agent was: `Mozilla/5.0 (Windows NT 6.0; WOW64; rv:9.0.1) Gecko/20100101 Firefox/9.0.1`

==== System Information ====

|| '''Trac''' || `0.11.7.ja1` ||
|| '''Python''' || `2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)]` ||
|| '''setuptools''' || `0.6` ||
|| '''SQLite''' || `3.6.21` ||
|| '''pysqlite''' || `2.6.0` ||
|| '''Genshi''' || `0.6` ||
|| '''mod_wsgi''' || `3.3 (WSGIProcessGroup  WSGIApplicationGroup %{GLOBAL})` ||
|| '''Subversion''' || `1.7.1 (r1186859)` ||
|| '''jQuery:''' || `1.2.6` ||

==== Python Traceback ====
{{{
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\trac-0.11.7.ja1-py2.7.egg\trac\web\main.py", line 450, in _dispatch_request
    dispatcher.dispatch(req)
  File "C:\Python27\lib\site-packages\trac-0.11.7.ja1-py2.7.egg\trac\web\main.py", line 206, in dispatch
    resp = chosen_handler.process_request(req)
  File "C:\Python27\lib\site-packages\trac-0.11.7.ja1-py2.7.egg\trac\ticket\web_ui.py", line 184, in process_request
    return self._process_newticket_request(req)
  File "C:\Python27\lib\site-packages\trac-0.11.7.ja1-py2.7.egg\trac\ticket\web_ui.py", line 409, in _process_newticket_request
    self._do_create(req, ticket) # (redirected if successful)
  File "C:\Python27\lib\site-packages\trac-0.11.7.ja1-py2.7.egg\trac\ticket\web_ui.py", line 1011, in _do_create
    ticket.insert()
  File "C:\Python27\lib\site-packages\trac-0.11.7.ja1-py2.7.egg\trac\ticket\model.py", line 215, in insert
    listener.ticket_created(self)
  File "build\bdist.win32\egg\ticket2rtm\ticket2rtm.py", line 46, in ticket_created
    self.create_task(ticket)
  File "build\bdist.win32\egg\ticket2rtm\ticket2rtm.py", line 35, in create_task
    ticket['priority'])
  File "build\bdist.win32\egg\ticket2rtm\rtm.py", line 113, in add_task
    url = self.api.make_req_url('rtm.tasks.add', params)
  File "build\bdist.win32\egg\ticket2rtm\rtm.py", line 28, in make_req_url
    args['api_sig'] = self.sign(args)
  File "build\bdist.win32\egg\ticket2rtm\rtm.py", line 23, in sign
    return md5.new(str).hexdigest()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 146-149: ordinal not in range(128)

}}}

**Comment by markeyev** [comment]
I seriously hope that you will fix this issue.
